baseURL: "https://blog.sysmango.net/"
languageCode: "en-us"
title: "SysMango.com"
theme: "PaperModX"
params:
  AuthorName: ButchLebo
  GitHubUser: butchlebo
  Subtitle: The gears in my mind never stop turning . . . 
enableGitInfo: true
enableRobotsTXT: true

