baseURL: "https://sysmango.com/"
languageCode: "en-us"
title: "SysMango.com"
theme: "PaperMod"
params:
  AuthorName: ButchLebo
  GitHubUser: butchlebo
  Subtitle: The gears in my mind never stop turning . . . 
  googleAnalyticsID: G-60431XR3D9
enableGitInfo: true
enableRobotsTXT: true
googleAnalytics: G-60431XR3D9


services:
  googleAnalytics:
    ID: G-60431XR3D9


