baseURL: "https://sysmango.com/"
languageCode: "en-us"
title: "SysMango.com"
theme: "sysmango"
params:
  env: production
  AuthorName: ButchLebo
  GitHubUser: butchlebo
  Subtitle: The gears in my mind never stop turning . . . 
  googleAnalyticsID: G-60431XR3D9
  flickrApiKey: "ff1d1b6cf7979c1a25d742af946ce957"
enableGitInfo: true
enableRobotsTXT: true
googleAnalytics: G-60431XR3D9
services:
  googleAnalytics:
    ID: G-60431XR3D9
privacy:
    googleAnalytics:
        disable: false

