baseURL: "https://sysmango.com/"
languageCode: "en-us"
title: "SysMango.com"
theme: "mainroad"
params:
  AuthorName: ButchLebo
  GitHubUser: butchlebo
  Subtitle: The gears in my mind never stop turning . . . 
enableGitInfo: true
enableRobotsTXT: true
googleAnalytics: UA-4643595-2

