services:
  - type: web
    name: sysmangodotcom
    env: static
    buildCommand: hugo --minify
    staticPublishPath: ./public
    pullRequestPreviewsEnabled: true
    envVars:
      - key: HUGO_VERSION
        value: 0.111.3
      - key: FLICKR_API_KEY
        sync: false
    buildFilter:
      paths:
        - content/**/*
        - static/**/*
        - themes/**/*
        - config.yaml
        - config.toml
        - config/_default/**/*
